CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "role" varchar,
  "phone" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "trucks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" int,
  "licence_plate" varchar,
  "model" varchar,
  "capacity" int,
  "frequent_location" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "availability" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "available_from" datetime,
  "available_to" datetime,
  "current_location" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "job_posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "pickup_location" varchar,
  "dropoff_location" varchar,
  "pickup_time" datetime,
  "title" varchar(100),
  "description" text,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_post_id" int,
  "truck_id" int,
  "bid_price" decimal,
  "estimated_delivery_time" datetime,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "feedbacks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" int,
  "user_id" int,
  "truck_id" int,
  "rating" int,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "chat_messages" (
  "message_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" int,
  "sender_id" int,
  "receiver_id" int,
  "message" text,
  "created_at" timestamp DEFAULT 'CURRENT_TIMESTAMPS',
  "read_status" boolean DEFAULT false
);

CREATE TABLE "vehicle_safety" (
  "safety_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" int NOT NULL,
  "insurance_expiry" date NOT NULL,
  "technical_control_expiry" date NOT NULL,
  "yellow_card" longblob,
  "current_mileage" int NOT NULL,
  "fuel_consumption" decimal(5,2),
  "last_updated" timestamp DEFAULT 'CURRENT_TIMESTAMP'
);

CREATE TABLE "vehicles" (
  "vehicle_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "driver_id" int NOT NULL,
  "yellow_card" LONGBLOB,
  "plate_no" varchar(20) NOT NULL,
  "total_kilometers" int,
  "model" varchar(50),
  "capacity" int,
  "frequent_location" varchar(100),
  "status" varchar(20),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

COMMENT ON COLUMN "vehicles"."updated_at" IS 'Automatically update on modification';

ALTER TABLE "trucks" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "availability" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "job_posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("job_post_id") REFERENCES "job_posts" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("truck_id") REFERENCES "trucks" ("id");

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("truck_id") REFERENCES "trucks" ("id");

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id");

ALTER TABLE "vehicle_safety" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("vehicle_id");

ALTER TABLE "vehicles" ADD FOREIGN KEY ("driver_id") REFERENCES "trucks" ("id");

ALTER TABLE "job_posts" ADD FOREIGN KEY ("description") REFERENCES "job_posts" ("id");
